version: "3.7"

services:
  app_proxy:
    image: getumbrel/app-proxy:v0.1.0
    environment:
      APP_HOST: matterbridge_server_1
      APP_PORT: 8283
    restart: on-failure

  server:
    container_name: matterbridge_server_1
    image: luligu/matterbridge:latest
    network_mode: host
    restart: always
    volumes:
      - "${APP_DATA_DIR}/data/Matterbridge:/root/Matterbridge"
      - "${APP_DATA_DIR}/data/.matterbridge:/root/.matterbridge"
      - "${APP_DATA_DIR}/data/.mattercert:/root/.mattercert"