services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: nico-matterbridge_server_1
      APP_PORT: 8283

  server:
    image: luligu/matterbridge:latest
    network_mode: host
    restart: unless-stopped
    user: "1000:1000"
    volumes:
      - "${APP_DATA_DIR}/data/Matterbridge:/root/Matterbridge"
      - "${APP_DATA_DIR}/data/.matterbridge:/root/.matterbridge"
      - "${APP_DATA_DIR}/data/.mattercert:/root/.mattercert"